// Simulates what a PDF extraction service would return for each invoice
// in an uploaded batch, per the SDD's extraction step. Swap this module
// for a real POST /api/invoices/extract call when the backend exists —
// nothing in the components needs to change.
export const sampleExtractedBatch = [
  {
    vendorName: "Namib Freight Logistics",
    amount: 84250,
    currency: "USD",
    extractedBankCountry: "Namibia",
    extractedRoutingNumber: "NA76-8801-2200-1123-4455",
    extractedEmailDomain: "namibfreight.na",
    extractionStatus: "complete" as const,
  },
  {
    vendorName: "Namib Freight Logistics",
    amount: 79100,
    currency: "USD",
    extractedBankCountry: "Namibia",
    extractedRoutingNumber: "NA76-8801-2200-1123-4455",
    extractedEmailDomain: "namibfreight.na",
    extractionStatus: "complete" as const,
  },
  {
    vendorName: "ACME Industrial Manufacturing",
    amount: 612000,
    currency: "EUR",
    extractedBankCountry: "Cyprus",
    extractedRoutingNumber: "CY24-1122-3300-9988-7766",
    extractedEmailDomain: "acme-manufacturing.com",
    extractionStatus: "complete" as const,
  },
  {
    vendorName: "Silverline Components Ltd",
    amount: 143500,
    currency: "GBP",
    extractedBankCountry: "United Kingdom",
    extractedRoutingNumber: "GB29-NWBK-6016-1355-0042-11",
    extractedEmailDomain: "silverline-components.co.uk",
    extractionStatus: "complete" as const,
  },
  {
    vendorName: "Pinnacle Steel Trading",
    amount: 92750,
    currency: "USD",
    extractedBankCountry: "South Africa",
    extractedRoutingNumber: "ZA45-2200-1188-7766",
    extractedEmailDomain: "pinnaclesteel-invoices.co.za",
    extractionStatus: "complete" as const,
  },
  {
    vendorName: "Meridian Textiles Co",
    amount: 51900,
    currency: "EUR",
    extractedBankCountry: "Portugal",
    extractedRoutingNumber: "PT50-0002-0123-1234-5678-901-54",
    extractedEmailDomain: "meridiantextiles.pt",
    extractionStatus: "complete" as const,
  },
  {
    vendorName: "Coastal Marine Parts",
    amount: 38400,
    currency: "USD",
    extractedBankCountry: "Kenya",
    extractedRoutingNumber: "KE12-4400-9911-2233",
    extractedEmailDomain: "coastalmarine.ke",
    extractionStatus: "complete" as const,
  },
  {
    vendorName: "Pinnacle Steel Trading",
    amount: 67300,
    currency: "USD",
    extractedBankCountry: "South Africa",
    extractedRoutingNumber: "ZA45-2200-1188-7766",
    extractedEmailDomain: "pinnaclesteel.co.za",
    extractionStatus: "complete" as const,
  },
  {
    vendorName: "Vantage Global Traders",
    amount: 214000,
    currency: "USD",
    extractedBankCountry: "Hong Kong",
    extractedRoutingNumber: "HK88-2200-1199-3344",
    extractedEmailDomain: "vantageglobaltraders.com",
    extractionStatus: "complete" as const,
  },
  {
    vendorName: "Silverline Components Ltd",
    amount: 28900,
    currency: "GBP",
    extractedBankCountry: "United Kingdom",
    extractedRoutingNumber: "GB29-NWBK-6016-1331-9268-19",
    extractedEmailDomain: "silverline-components.co.uk",
    extractionStatus: "complete" as const,
  },
];
